AWSTemplateFormatVersion: 2010-09-09
Description: security alarm

Parameters:
  TrailLogGroupName:
    Type: String
  MetricNamespace:
    Type: String
    Default: TrailLogMetrics
  SNSTopicName:
    Type: String
    Default: SecurityAlarm
  SNSDisplayName:
    Type: String
    Default: SecurityAlarm
  # 通知先が複数ならばメーリングリストが良い
  SecurityAlarmEmailAddress: 
    Type: String
    Default: '{{resolve:ssm:SecurityAlarmEmailAddress:1}}'

Resources:
  SecurityAlarmSNS:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Ref SNSTopicName
      DisplayName: !Ref SNSDisplayName
      # SNSの暗号化とは？
      # KmsMasterKeyId: String
      Subscription:
        - Endpoint: !Ref SecurityAlarmEmailAddress
          Protocol: email
  
  #----------------------------------------------------------------------------
  # 許可されていないAPIコールに対するアラーム通知設定
  #----------------------------------------------------------------------------
  UnauthorizedAPICallsFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: '{($.errorCode="*UnauthorizedOperation") || ($.errorCode="AccessDenied*")}'
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: UnauthorizedAPICalls
          MetricValue: '1'
  
  UnauthorizedAPICallsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: UnauthorizedAPICallsAlarm
      AlarmDescription: Alarm cloudtrail detected unauthorized API calls
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: UnauthorizedAPICalls
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      # 以下2つのみをもう少し詳しく知りたい
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  #----------------------------------------------------------------------------
  # MFAなしでのAWSマネージメントコンソールログインに対してのアラーム通知設定
  #----------------------------------------------------------------------------
  LoginWithoutMFAFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: '{($.eventName = "ConsoleLogin") && ($.additionalEventData.MFAUsed != "Yes")}'
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: LoginWithoutMFA
          MetricValue: '1'
  
  LoginWithoutMFAAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: LoginWithoutMFAAlarm
      AlarmDescription: Alarm cloudtrail detected console login without MFA
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: LoginWithoutMFA
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  #----------------------------------------------------------------------------
  # IAMポリシーの変更を検知するアラーム
  #----------------------------------------------------------------------------
  IAMPolicyChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        {($.eventName=DeleteGroupPolicy) || ($.eventName=DeleteRolePolicy)
        || ($.eventName=DeleteUserPolicy) || ($.eventName=PutGroupPolicy)
        || ($.eventName=PutRolePolicy) || ($.eventName=PutUserPolicy)
        || ($.eventName=CreatePolicy) || ($.eventName=DeletePolicy)
        || ($.eventName=CreatePolicyVersion) || ($.eventName=DeletePolicyVersion)
        || ($.eventName=AttachRolePolicy) || ($.eventName=DetachRolePolicy)
        || ($.eventName=AttachUserPolicy) || ($.eventName=DetachUserPolicy)
        || ($.eventName=AttachGroupPolicy) || ($.eventName=DetachGroupPolicy)}
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: IAMPolicyChange
          MetricValue: '1'
  
  IAMPolicyChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: IAMPolicyChangeAlarm
      AlarmDescription: Alarm cloudtrail detected　IAM policy changes 
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: IAMPolicyChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  
  
  #----------------------------------------------------------------------------
  # CloudTrail設定の変更を検知するアラームを作成する
  #----------------------------------------------------------------------------
  CloudTrailConfigChangeFilter :
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        {($.eventName = CreateTrail) || ($.eventName = UpdateTrail)
        || ($.eventName =DeleteTrail) || ($.eventName = StartLogging) 
        || ($.eventName = StopLogging)}
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: CloudTrailConfigChange
          MetricValue: '1'
  
  CloudTrailConfigChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: CloudTrailConfigChangeAlarm
      AlarmDescription: Alarm cloudtrail detected　CloudTrail config changes 
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: CloudTrailConfigChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching