AWSTemplateFormatVersion: 2010-09-09
Description: security alarm

Parameters:
  TrailLogGroupName:
    Type: String
  MetricNamespace:
    Type: String
    Default: TrailLogMetrics
  SNSTopicName:
    Type: String
    Default: SecurityAlarm
  SNSDisplayName:
    Type: String
    Default: SecurityAlarm
  # 通知先が複数ならばメーリングリストが良い
  SecurityAlarmEmailAddress: 
    Type: String
    Default: '{{resolve:ssm:SecurityAlarmEmailAddress:1}}'

Resources:
  SecurityAlarmSNS:
    Type: "AWS::SNS::Topic"
    Properties:
      TopicName: !Ref SNSTopicName
      DisplayName: !Ref SNSDisplayName
      # SNSの暗号化とは？
      # KmsMasterKeyId: String
      Subscription:
        - Endpoint: !Ref SecurityAlarmEmailAddress
          Protocol: email
  
  #----------------------------------------------------------------------------
  # 許可されていないAPIコールに対するアラーム通知設定
  #----------------------------------------------------------------------------
  UnauthorizedAPICallsFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: '{($.errorCode="*UnauthorizedOperation") || ($.errorCode="AccessDenied*")}'
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: UnauthorizedAPICalls
          MetricValue: '1'
  
  UnauthorizedAPICallsAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: UnauthorizedAPICallsAlarm
      AlarmDescription: Alarm cloudtrail detected unauthorized API calls
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: UnauthorizedAPICalls
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      # 以下2つのみをもう少し詳しく知りたい
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  #----------------------------------------------------------------------------
  # MFAなしでのAWSマネージメントコンソールログインに対してのアラーム通知設定
  #----------------------------------------------------------------------------
  LoginWithoutMFAFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: '{($.eventName = "ConsoleLogin") && ($.additionalEventData.MFAUsed != "Yes")}'
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: LoginWithoutMFA
          MetricValue: '1'
  
  LoginWithoutMFAAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: LoginWithoutMFAAlarm
      AlarmDescription: Alarm cloudtrail detected console login without MFA
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: LoginWithoutMFA
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  #----------------------------------------------------------------------------
  # IAMポリシーの変更を検知するアラーム
  #----------------------------------------------------------------------------
  IAMPolicyChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        {($.eventName=DeleteGroupPolicy) || ($.eventName=DeleteRolePolicy)
        || ($.eventName=DeleteUserPolicy) || ($.eventName=PutGroupPolicy)
        || ($.eventName=PutRolePolicy) || ($.eventName=PutUserPolicy)
        || ($.eventName=CreatePolicy) || ($.eventName=DeletePolicy)
        || ($.eventName=CreatePolicyVersion) || ($.eventName=DeletePolicyVersion)
        || ($.eventName=AttachRolePolicy) || ($.eventName=DetachRolePolicy)
        || ($.eventName=AttachUserPolicy) || ($.eventName=DetachUserPolicy)
        || ($.eventName=AttachGroupPolicy) || ($.eventName=DetachGroupPolicy)}
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: IAMPolicyChange
          MetricValue: '1'
  
  IAMPolicyChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: IAMPolicyChangeAlarm
      AlarmDescription: Alarm cloudtrail detected　IAM policy changes 
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: IAMPolicyChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  
  
  #----------------------------------------------------------------------------
  # CloudTrail設定の変更を検知するアラーム
  #----------------------------------------------------------------------------
  CloudTrailConfigChangeFilter :
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        {($.eventName = CreateTrail) || ($.eventName = UpdateTrail)
        || ($.eventName =DeleteTrail) || ($.eventName = StartLogging) 
        || ($.eventName = StopLogging)}
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: CloudTrailConfigChange
          MetricValue: '1'
  
  CloudTrailConfigChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: CloudTrailConfigChangeAlarm
      AlarmDescription: Alarm cloudtrail detected　CloudTrail config changes 
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: CloudTrailConfigChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  
  #----------------------------------------------------------------------------
  # AWSマネージメントコンソールのログイン失敗を検知するアラーム
  #----------------------------------------------------------------------------
  ManagementConsoleAuthFailureFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: '{($.eventName = ConsoleLogin) && ($.errorMessage = "Failed authentication")}'
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: ManagementConsoleAuthFailure
          MetricValue: '1'
    
  ManagementConsoleAuthFailureAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: ManagementConsoleAuthFailureAlarm
      AlarmDescription: Alarm cloudtrail detected management console login failure 
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: ManagementConsoleAuthFailure
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  

  #----------------------------------------------------------------------------
  # KMSマスターキー(CMK)の無効化またはスケジュール削除を検知するアラーム
  #----------------------------------------------------------------------------
  CMKChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        {($.eventSource = kms.amazonaws.com) &&
        (($.eventName=DisableKey)||($.eventName=ScheduleKeyDeletion))}
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: CMKChange
          MetricValue: '1'
    
  CMKChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: CMKChangeAlarm
      AlarmDescription: Alarm cloudtrail detected CMK changes
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: CMKChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
  

  #----------------------------------------------------------------------------
  # S3バケットポリシー変更を検知するアラーム
  #----------------------------------------------------------------------------
  S3BucketPolicyChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        { ($.eventSource = s3.amazonaws.com) && 
        (($.eventName = PutBucketAcl) || ($.eventName = PutBucketPolicy)
        || ($.eventName = PutBucketCors) || ($.eventName = PutBucketLifecycle) 
        || ($.eventName = PutBucketReplication) || ($.eventName = DeleteBucketPolicy) 
        || ($.eventName = DeleteBucketCors) || ($.eventName = DeleteBucketLifecycle) 
        || ($.eventName = DeleteBucketReplication)) }
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: S3BucketPolicyChange
          MetricValue: '1'
    
  S3BucketPolicyChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: S3BucketPolicyChange
      AlarmDescription: Alarm cloudtrail detected S3Bucket policy changes
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: S3BucketPolicyChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching
    
  
  #----------------------------------------------------------------------------
  # セキュリティグループ変更を検知するアラームを作成する
  #----------------------------------------------------------------------------
  SecurityGroupChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        { ($.eventName = AuthorizeSecurityGroupIngress) 
        || ($.eventName = AuthorizeSecurityGroupEgress) 
        || ($.eventName = RevokeSecurityGroupIngress) 
        || ($.eventName = RevokeSecurityGroupEgress) 
        || ($.eventName = CreateSecurityGroup) 
        || ($.eventName = DeleteSecurityGroup) }
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: S3BucketPolicyChange
          MetricValue: '1'
    
  SecurityGroupChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: SecurityGroupChangeAlarm
      AlarmDescription: Alarm cloudtrail detected security group changes
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: SecurityGroupChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  
  #----------------------------------------------------------------------------
  # ネットワークACLの変更を検知するアラームを作成する
  #----------------------------------------------------------------------------
  NetworkAclChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        { ($.eventName = CreateNetworkAcl) 
        || ($.eventName = CreateNetworkAclEntry) 
        || ($.eventName = DeleteNetworkAcl) 
        || ($.eventName = DeleteNetworkAclEntry) 
        || ($.eventName = ReplaceNetworkAclEntry) 
        || ($.eventName = ReplaceNetworkAclAssociation) }
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: NetworkAclChange
          MetricValue: '1'
    
  NetworkAclChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: NetworkAclChangeAlarm
      AlarmDescription: Alarm cloudtrail detected network acl changes
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: NetworkAclChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching


  #----------------------------------------------------------------------------
  # インターネットゲートウェイ変更を検知するアラーム
  #----------------------------------------------------------------------------
  InternetGatewayChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        { ($.eventName = CreateCustomerGateway) 
        || ($.eventName = DeleteCustomerGateway) 
        || ($.eventName = AttachInternetGateway) 
        || ($.eventName = CreateInternetGateway) 
        || ($.eventName = DeleteInternetGateway) 
        || ($.eventName = DetachInternetGateway) }
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: InternetGatewayChange
          MetricValue: '1'
    
  InternetGatewayChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: InternetGatewayChangeAlarm
      AlarmDescription: Alarm cloudtrail detected internet gateway changes
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: InternetGatewayChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching

  
  #----------------------------------------------------------------------------
  # ルートテーブル変更を検知するアラーム
  #----------------------------------------------------------------------------
  RouteTableChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        { ($.eventName = CreateRoute) 
        || ($.eventName = CreateRouteTable) 
        || ($.eventName = ReplaceRoute) 
        || ($.eventName = ReplaceRouteTableAssociation) 
        || ($.eventName = DeleteRouteTable) 
        || ($.eventName = DeleteRoute) 
        || ($.eventName = DisassociateRouteTable) }
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: RouteTableChange
          MetricValue: '1'
    
  RouteTableChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: RouteTableChangeAlarm
      AlarmDescription: Alarm cloudtrail detected route table changes
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: RouteTableChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching


  #----------------------------------------------------------------------------
  # VPC変更を検知するアラーム
  #----------------------------------------------------------------------------
  VPCChangeFilter:
    Type: "AWS::Logs::MetricFilter"
    Properties:
      FilterPattern: >-
        { ($.eventName = CreateVpc) 
        || ($.eventName = DeleteVpc) 
        || ($.eventName = ModifyVpcAttribute) 
        || ($.eventName = AcceptVpcPeeringConnection) 
        || ($.eventName = CreateVpcPeeringConnection) 
        || ($.eventName = DeleteVpcPeeringConnection) 
        || ($.eventName = RejectVpcPeeringConnection) 
        || ($.eventName = AttachClassicLinkVpc) 
        || ($.eventName = DetachClassicLinkVpc) 
        || ($.eventName = DisableVpcClassicLink) 
        || ($.eventName = EnableVpcClassicLink) }
      LogGroupName: !Ref TrailLogGroupName
      MetricTransformations:
        - MetricNamespace: !Ref MetricNamespace
          MetricName: VPCChange
          MetricValue: '1'
    
  VPCChangeAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: VPCChangeAlarm
      AlarmDescription: Alarm cloudtrail detected vpc changes
      ActionsEnabled: true
      Namespace: !Ref MetricNamespace
      MetricName: VPCChange
      AlarmActions:
        - !Ref SecurityAlarmSNS
      ComparisonOperator: GreaterThanOrEqualToThreshold 
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
      Period: 300
      Statistic: Sum
      Threshold: 1
      TreatMissingData: notBreaching